---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nc0009-glenn-school-store
  namespace: default
spec:
  repo: https://teknoir.github.io/victra-poc-helm
  chart: victra-poc
  version: 0.1.0-beta.2
  targetNamespace: default
  valuesContent: |-
    nvr:
      defaults:
        debugLevel: DEBUG

        camera:
          motion:
            inactiveInterval: 900
            activeInterval: 3          
          pipeline: "{{ template \"defaultPipeline\" . }}"
  
      instances:
        - name: nc0009-pos
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.113/stream1
            pipelineValues:
              rtspSrc:
                width: 2688
                height: 1520
  
        - name: nc0009-back-door
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.116/stream1
            pipelineValues:
              rtspSrc:
                width: 2688
                height: 1520
  
        - name: nc0009-front-door
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"nvdsanalyticsPipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 2560
                height: 1440
          nvdsanalytics:
            enabled: true
            config: |
              [property]
              enable=1
              config-width=1920
              config-height=1080
              osd-mode=0
              display-font-size=25

              [line-crossing-stream-0]
              enable=1
              extended=0
              line-crossing-Entry-0=980;574;966;773;847;765;1084;782
              line-crossing-Exit-0=951;973;966;773;1084;782;847;765

        - name: nc0009-height-strip
          camera:
            uri: rtsp://root:Redex1997!@192.168.51.117/live1s1.sdp

        - name: nc0009-backroom-safe-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=0
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0

        - name: nc0009-backroom-safe-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
    
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=90
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0
    
        - name: nc0009-backroom-safe-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
    
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=180
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0

        - name: nc0009-backroom-safe-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
    
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=270
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0
  
        - name: nc0009-salefloor-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=0
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0

        - name: nc0009-salefloor-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=90
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0

        - name: nc0009-salefloor-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=180
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0

        - name: nc0009-salefloor-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
              jpegMQTT:
                width: 2000
                height: 1500
          nvdewarper:
            enabled: true
            config: |
              [property]
              enable=1
              source-id=0
              output-width=2000
              output-height=1500
              num-batch-buffers=1
              [surface0]
              surface-index=0
              projection-type=4
              width=2000
              height=1500
              rot-axes=ZXY
              pitch=50
              yaw=0
              roll=270
              src-fov=180
              src-x0=2000
              src-y0=1500
              focal-length=960
              distortion=0;0;0;0
    
    observatory-pipeline:
      defaults:
        debugLevel: DEBUG

        image:
          tag: dev-0f0ec07
      
        labels:
          deviceID: "victra-poc-02"
    
      streams:
        - stream: update-frame-rate-control
        - stream: record-detections
        - stream: update-movements
        - stream: compreface
          mqtt:
            topicFaces: "toe/events/faces"
          facerec:
            compreFaceApiKey: "00000000-0000-0000-0000-000000000002"
            faceRecThreshold: 0.9
            faceImageSize: 100
        # ALERTS
        - stream: loitering
        - stream: person-down
        - stream: line-crossing
        - stream: hands-up
        - stream: running
        - stream: face-cover
        - stream: weapons
        - stream: safe-open
        # ALERT PROCESSING
        - stream: update-alerts

      file-transfer:
        defaults:
          labels:
            deviceID: "victra-poc-02"
