---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nc0009-glenn-school-store
  namespace: default
spec:
  repo: https://teknoir.github.io/victra-poc-helm
  chart: victra-poc
  version: 0.1.2-beta.14
  targetNamespace: default
  valuesContent: |-
    nvr:
      defaults:
        debugLevel: DEBUG

        camera:
          pipeline: "{{ template \"defaultPipeline\" . }}"
  
      instances:
        - name: nc0009-pos
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.113/stream1
            pipeline: "{{ template \"defaultPipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 2688
                height: 1520

  
        - name: nc0009-back-door
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.116/stream1
            pipeline: "{{ template \"defaultPipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 2688
                height: 1520

  
        - name: nc0009-front-door
          camera:
            motion:
              activeInterval: "0"
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"defaultPipelineAccuracyTracker\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 2560
                height: 1440


        - name: nc0009-height-strip
          camera:
            uri: rtsp://root:Redex1997!@192.168.51.117/live1s1.sdp
            pipeline: "{{ template \"defaultPipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              

        - name: nc0009-backroom-safe-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 0


        - name: nc0009-backroom-safe-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 90

    
        - name: nc0009-backroom-safe-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 180


        - name: nc0009-backroom-safe-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360PipelineAccuracyTracker\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 270

  
        - name: nc0009-salefloor-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 0


        - name: nc0009-salefloor-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 90


        - name: nc0009-salefloor-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 180


        - name: nc0009-salefloor-270
          camera:
            motion:
              activeInterval: "0" # Has to be a string or it is interpreted as null
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream1
            pipeline: "{{ template \"default360PipelineAccuracyTracker\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 270

    
    observatory-pipeline:
      defaults:
        debugLevel: DEBUG

        image:
          tag: feature-dead-reconing-fix-cda0567
          #tag: dev-6b3671d
      
        labels:
          deviceID: "victra-poc-02"

        roiStreamConfig:
          enabled: true
          peripherals:
            - name: nc0009-pos
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;20;0;65;279;433;111;425;38;462;0;540;0;612;46;785;0;1920;0;1920;1080;0;1080"
                roi-face_cover-Exclusion-Zone-1: "1306;2;1306;44;1634;42;1634;1"

            - name: nc0009-back-door
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"
              lc-config:                
                lc-back-room-Entry-0: "705;586;745;782;590;813;899;750"
                lc-back-room-Exit-0: "784;978;745;782;899;750;590;813"

            - name: nc0009-front-door
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;689;758;800;1122;824;1586;827;1920;792;1920;1080;0;1080"
                roi-face_cover-Exclusion-Zone-1: "0;0;0;500;1920;500;1920;0"

            - name: nc0009-height-strip
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0009-backroom-safe-0
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0009-backroom-safe-90
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0009-backroom-safe-180
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"
              lc-config:
                lc-back-room-Entry-0: "892;452;883;652;794;648;973;656"
                lc-back-room-Exit-0: "874;852;883;652;973;656;794;648"

            - name: nc0009-backroom-safe-270
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0009-salefloor-0
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;865;484;274;407;0;1920;0;1920;1080;0;1080"

            - name: nc0009-salefloor-90
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0009-salefloor-180
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1903;0;1689;441;1920;766;1920;1080;0;1080"

            - name: nc0009-salefloor-270
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;68;0;68;49;353;472;1920;532;1920;1080;0;1080"
              lc-config:
                lc-Entry-0: "1180;284;1171;484;1082;480;1259;488"
                lc-Exit-0: "1161;683;1171;484;1259;488;1082;480"
      
      streams:
        - stream: update-frame-rate-control
        - stream: record-detections
        - stream: update-movements
        - stream: compreface
          mqtt:
            topicFaces: "toe/events/faces"
          facerec:
            compreFaceApiKey: "00000000-0000-0000-0000-000000000002"
            faceRecThreshold: 0.992
        # ALERTS
        - stream: loitering
        - stream: person-down
        - stream: line-crossing
        - stream: hands-up
        - stream: running
        - stream: weapons
          alerts:
            weaponCutoutMinSize: 0
          weaponsDetection:
            scoreThreshold: 0.3
            window: 1
        - stream: safe-open
        - stream: backdoor-open
        - stream: facerec-cutout
        - stream: person-cutout
        - stream: pos-event
          video:
            segmentRetentionLength: 8640
        - stream: alarm-event
        - stream: unauthorized-entry
        - stream: face-cover-detections
          faceCoverDetection:
            threshold: 0.9
            windowSize: 8000
            slidingInterval: 1000
        - stream: extended-occupancy
        # ALERT PROCESSING
        - stream: update-alerts
          video:
            segmentRetentionLength: 8640

      file-transfer:
        defaults:
          image:
            tag: dev-c0862d1
          labels:
            deviceID: "victra-poc-02"

      # DEBUG NOT FOR PRODUCTION
      clickhouse:
        nodePort:
          enabled: true
      keydb:
        nodePort:
          enabled: true