---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nc0211-lexington-store
  namespace: default
spec:
  repo: https://teknoir.github.io/victra-poc-helm
  chart: victra-poc
  version: 0.1.1-beta.6
  targetNamespace: default
  valuesContent: |-
    nvr:
      defaults:
        debugLevel: DEBUG

        camera:
          pipeline: "{{ template \"defaultPipeline\" . }}"

      instances:
        - name: nc0211-pos
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.113/stream1

        - name: nc0211-height-strip
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/live.sdp

        - name: nc0211-front-door-1
          camera:
            motion:
              activeInterval: "0"
            uri: rtsp://admin:Redex1997!@192.168.51.117/stream1
            pipeline: "{{ template \"nvdsanalyticsPipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 2560
                height: 1440
          nvdsanalytics:
            enabled: true
            config: |
              [property]
              enable=1
              config-width=1920
              config-height=1080
              osd-mode=0
              display-font-size=25
              [line-crossing-stream-0]
              enable=1
              extended=1
              line-crossing-Entry-0=893;513;872;712;746;698;997;726
              line-crossing-Exit-0=850;911;872;712;997;726;746;698

        - name: nc0211-front-door-2
          camera:
            motion:
              activeInterval: "0"
            uri: rtsp://admin:Redex1997!@192.168.51.116/live.sdp
            pipeline: "{{ template \"nvdsanalyticsPipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 2560
                height: 1440
          nvdsanalytics:
            enabled: true
            config: |
              [property]
              enable=1
              config-width=1920
              config-height=1080
              osd-mode=0
              display-font-size=25
              [line-crossing-stream-0]
              enable=1
              extended=1
              line-crossing-Entry-0=1001;472;1003;672;878;673;1127;671
              line-crossing-Exit-0=1004;872;1003;672;1127;671;878;673
    
        - name: nc0211-backroom-safe-door-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 0

    
        - name: nc0211-backroom-safe-door-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 90


        - name: nc0211-backroom-safe-door-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 180

    
        - name: nc0211-backroom-safe-door-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 270

    
        - name: nc0211-safe-back-door-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 0

    
        - name: nc0211-safe-back-door-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 90

    
        - name: nc0211-safe-back-door-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 180

    
        - name: nc0211-safe-back-door-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 40
            roll: 270
  

        - name: nc0211-sales-floor-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 0


        - name: nc0211-sales-floor-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 90

    
        - name: nc0211-sales-floor-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 180


        - name: nc0211-sales-floor-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 270

    observatory-pipeline:
      defaults:
        debugLevel: DEBUG

        image:
          tag: dev-c82c317

        labels:
          deviceID: "victra-poc-03"

      streams:
        - stream: update-frame-rate-control
        - stream: record-detections
        - stream: update-movements
        - stream: compreface
          mqtt:
            topicFaces: "toe/events/faces"
          facerec:
            compreFaceApiKey: "00000000-0000-0000-0000-000000000002"
            faceRecThreshold: 0.9
            faceImageSize: 100
        # ALERTS
        - stream: loitering
        - stream: person-down
        - stream: line-crossing
        - stream: hands-up
        - stream: running
        - stream: face-cover
        - stream: weapons
        - stream: safe-open
        # ALERT PROCESSING
        - stream: update-alerts

      file-transfer:
        defaults:
          labels:
            deviceID: "victra-poc-03"
            
      # DEBUG NOT FOR PRODUCTION
      clickhouse:
        nodePort:
          enabled: true
      keydb:
        nodePort:
          enabled: true
