---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nc0211-lexington-store
  namespace: default
spec:
  repo: https://teknoir.github.io/victra-poc-helm
  chart: victra-poc
  version: 0.1.2-beta.16
  targetNamespace: default
  valuesContent: |-
    nvr:
      defaults:
        debugLevel: DEBUG

        camera:
          pipeline: "{{ template \"defaultPipeline\" . }}"

      instances:
        - name: nc0211-pos
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.113/stream1
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
    

        - name: nc0211-height-strip
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/live.sdp
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
    

        - name: nc0211-front-door-1
          camera:
            motion:
              activeInterval: "0"
            uri: rtsp://admin:Redex1997!@192.168.51.117/stream1
            #pipeline: "{{ template \"defaultPipelineReIdSWINb1024Tracker\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 2560
                height: 1440


        - name: nc0211-front-door-2
          camera:
            motion:
              activeInterval: "0"
            uri: rtsp://admin:Redex1997!@192.168.51.116/live.sdp
            #pipeline: "{{ template \"defaultPipelineReIdSWINb1024Tracker\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 2560
                height: 1440

    
        #- name: nc0211-backroom-safe-door-0
        #  camera:
        #    uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
        #    pipeline: "{{ template \"default360Pipeline\" . }}"
        #    pipelineValues:
        #      rtspSrc:
        #        width: 4000
        #        height: 3000
        #  nvdewarper:
        #    enabled: true
        #    config: "{{ template \"360NvDeWarper\" . }}"
        #  nvdewarperValues:
        #    pitch: 30
        #    roll: 0
    
    
        - name: nc0211-backroom-safe-door-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 90


        - name: nc0211-backroom-safe-door-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 180
    
    
        - name: nc0211-backroom-safe-door-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.115/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 270
    
    
        - name: nc0211-safe-back-door-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 0
    
    
        #- name: nc0211-safe-back-door-90
        #  camera:
        #    uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
        #    pipeline: "{{ template \"default360Pipeline\" . }}"
        #    pipelineValues:
        #      rtspSrc:
        #        width: 4000
        #        height: 3000
        #  nvdewarper:
        #    enabled: true
        #    config: "{{ template \"360NvDeWarper\" . }}"
        #  nvdewarperValues:
        #    pitch: 30
        #    roll: 90
    
    
        - name: nc0211-safe-back-door-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 30
            roll: 180
    
    
        - name: nc0211-safe-back-door-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 40
            roll: 270
    
    
        - name: nc0211-sales-floor-0
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 0


        - name: nc0211-sales-floor-90
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 90
    
    
        - name: nc0211-sales-floor-180
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 180


        - name: nc0211-sales-floor-270
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
            pipeline: "{{ template \"default360Pipeline\" . }}"
            pipelineValues:
              videoRecorder:
                segmentCount: 8640
              rtspSrc:
                width: 4000
                height: 3000
          nvdewarper:
            enabled: true
            config: "{{ template \"360NvDeWarper\" . }}"
          nvdewarperValues:
            pitch: 50
            roll: 270
    

    observatory-pipeline:
      defaults:
        debugLevel: DEBUG

        image:
          #tag: dev-33e6cee
          tag: feature-sort-cutouts-1e67a9a

        labels:
          deviceID: "victra-poc-03"

        lineCrossing:
          intervalMs: 5000 # milliseconds
          windowMs: 10000 # milliseconds
          dejitterBatchMs: 10000 # milliseconds
          dejitterBatchCount: 3000
          
        roiStreamConfig:
          enabled: true
          peripherals:
            - name: nc0211-pos
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"
              lc-config:
                lc-pos-Entry-0=1029;380;1029;580;893;580;1165;580
                lc-pos-Exit-0=1029;780;1029;580;1165;580;893;580

            - name: nc0211-height-strip
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0211-front-door-1
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;425;0;406;472;726;499;719;698;1920;779;1920;1080;0;1090"
              lc-config:
                lc-Entry-0: "879;497;862;697;762;688;962;705"
                lc-Exit-0: "844;896;862;697;962;705;762;688"

            - name: nc0211-front-door-2
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;639;274;644;218;87;452;41;479;654;1129;650;1142;470;1498;471;1526;0;1920;0;1920;1080;0;1080"
              lc-config:
                lc-Entry-0: "997;448;998;648;900;649;1096;648"
                lc-Exit-0: "999;848;998;648;1096;648;900;649"
            #    lc-Entry-0: "1004;413;1007;613;910;615;1104;612"
            #    lc-Exit-0: "1010;813;1007;613;1104;612;910;615"

            - name: nc0211-backroom-safe-door-90
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"
              lc-config:                
                lc-back-room-Entry-0: "1354;502;1344;702;1171;693;1517;710"
                lc-back-room-Exit-0: "1334;901;1344;702;1517;710;1171;693"

            - name: nc0211-backroom-safe-door-180
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"
              lc-config:
                lc-back-room-Entry-0: "837;626;827;826;702;819;952;832"
                lc-back-room-Exit-0: "817;1025;827;826;952;832;702;819"

            - name: nc0211-backroom-safe-door-270
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0211-safe-back-door-0
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0211-safe-back-door-180
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0211-safe-back-door-270
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"
              lc-config:
                lc-back-room-Entry-0: "920;428;874;622;746;592;1002;653"
                lc-back-room-Exit-0: "827;817;874;622;1002;653;746;592"

            - name: nc0211-sales-floor-0
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0211-sales-floor-90
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;262;0;297;100;465;102;498;212;873;214;863;0;1054;0;1046;207;1433;215;1466;108;1663;111;1706;0;1920;0;1920;1080;0;1080"

            - name: nc0211-sales-floor-180
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

            - name: nc0211-sales-floor-270
              config-width: 1920
              config-height: 1080
              roi-config:
                roi-loitering-Exclusion-Zone-0: "0;0;1920;0;1920;1080;0;1080"

      streams:
        - stream: update-frame-rate-control
        - stream: record-detections
        - stream: update-movements
        - stream: compreface
          mqtt:
            topicFaces: "toe/events/faces"
          facerec:
            compreFaceApiKey: "00000000-0000-0000-0000-000000000002"
            faceRecThreshold: 0.992
        # ALERTS
        - stream: loitering
        - stream: person-down
        - stream: line-crossing
        - stream: hands-up
        - stream: running
        - stream: weapons
          #alerts:
          #  weaponCutoutMinSize: 0
          #weaponsDetection:
          #  scoreThreshold: 0.3
          #  window: 1
        - stream: safe-open
        - stream: backdoor-open
        - stream: facerec-cutout
        - stream: person-cutout
        - stream: pos-event
          video:
            segmentRetentionLength: 8640
        - stream: alarm-event
        - stream: unauthorized-entry
        - stream: face-cover-detections
          faceCoverDetection:
            threshold: 0.9
            windowSize: 8000
            slidingInterval: 1000
        - stream: extended-occupancy
        # ALERT PROCESSING
        - stream: update-alerts
          video:
            segmentRetentionLength: 8640

      file-transfer:
        defaults:
          image:
            tag: dev-c0862d1
          labels:
            deviceID: "victra-poc-03"
    
      # DEBUG NOT FOR PRODUCTION
      clickhouse:
        nodePort:
          enabled: true
      keydb:
        nodePort:
          enabled: true
