
triton:
  modelRepositoryPath: /opt/teknoir/models
  models:
    - name: rtdetr-wwfp
      image: us-docker.pkg.dev/teknoir/gcr.io/rtdetr-wwfp-triton:latest
    - name: resnet50-pose-estimation
      image:  us-docker.pkg.dev/teknoir/gcr.io/resnet50-pose-estimation-triton:latest-amd64-trt10.8-cc8.9-wwfp-20250520-071434
    - name: up-down-classifier
      image:  us-docker.pkg.dev/teknoir/gcr.io/up-down-classifier-triton:latest-amd64-trt10.8-cc8.9-wwfp-20250520-063931

nvr:
  defaults:
    camera:
      pipeline: "{{ template \"testPipeline\" . }}"
# The pipelineValues defaults are added through the pipeline templates in the templates folder
# Here is an example of how to set the pipeline values can be defined in each camera instance
#      pipelineValues:
#        rtspSrc:
#          width: 1920
#          height: 1080
#        jpegMQTT:
#          width: 1920
#          height: 1080
#          quality: 65
#        videoRecorder:
#          width: 1920
#          height: 1080
#          segmentSizeTime: 15
#          segmentCount: 2880
    mqtt:
      # Send events without inference calculated
      nonInferenceEvents: false
      # Send events without motion detected
      nonMotionEvents: true
    motion:
      # Number of frames to skip inference when no motion detected
      inactiveInterval: 900
      # Number of frames to skip inference when motion is detected
      activeInterval: 3
    image:
      # AMD64
      tag: ds7.1-gst1.24.12
    nvdsanalytics:
      enabled: true
      config: |
        [property]
        enable=0
        config-width=1920
        config-height=1080
        osd-mode=0
        display-font-size=25
    nvdewarper:
      enabled: true
      config: |
        [property]
        enable=1
        source-id=0
        output-width=2560
        output-height=1440
        num-batch-buffers=1
        [surface0]
        surface-index=0
        projection-type=4
        width=2560
        height=1440
        rot-axes=ZXY
        pitch=50
        yaw=0
        roll=270
        src-fov=180
        src-x0=2560
        src-y0=1440
        focal-length=960
        distortion=0;0;0;0
  instances: []
  
observatory-pipeline:
  defaults:
    debugLevel: INFO

    image:
      tag: weaponscore.3-not-committed

    labels:
      teamspace: "victra-poc"
      domain: "teknoir.cloud"

    historian:
      recordDetectionsInterval: 50 # ms
      objectsToFilter: "face,weapon,person" # not interested in vehicles

    alerts:
      alertHeatmapAlertsToFilter: "loitering,person_down,weapon,hands_up"
      alertHeatmapHardSupression: true

      personDownInterval: 10
      personDownScoreThreshold: 0.85
      personUpScoreThreshold: 0.75
      personDownUpTotalCountThreshold: 10

      handsUpInterval: 500 # milliseconds
      handsUpWindow: 1 # seconds
      minHandsUpDetectionsPerSecond: 0.9 # per second

    weaponsDetection:
      scoreThreshold: 0.8 # score threshold
      interval: 500 # milliseconds
      window: 1 # seconds
      minDetectionsPerSecond: 1.8 # per second

    clickhouse:
      detectionRetention: 1 # hours
      movementRetention: 24 # hours
      inferenceRetention: 1 # hours
      alertRetention: 24 # hours
      resources:
        limits:
          cpu: 2000m
          memory: 12Gi
        requests:
          cpu: 10m
          memory: 50Mi

    keydb:
      resources:
        limits:
          cpu: 2000m
          memory: 12Gi
        requests:
          cpu: 10m
          memory: 50Mi

    file-transfer:
      defaults:
        debugLevel: INFO

        labels:
          namespace: "victra-poc"
          domain: "teknoir.cloud"

        resources:
          limits:
            cpu: 2000m
            memory: 5Gi
          requests:
            cpu: 10m
            memory: 50Mi

