triton:
  modelRepositoryPath: /opt/teknoir/models
  models:
    - name: rtdetr
      image: us-docker.pkg.dev/teknoir/gcr.io/rtdetr-triton:latest-amd64-trt10.8-cc8.9-20250505-105553
    - name: rtdetr-weapons
      image: us-docker.pkg.dev/teknoir/gcr.io/rtdetr-weapons-triton:latest-amd64-trt10.8-cc8.9-v2-20250515-053841
    - name: resnet50-pose-estimation
      image:  us-docker.pkg.dev/teknoir/gcr.io/resnet50-pose-estimation-triton:latest-amd64-trt10.8-cc8.9-20250507-065729
    - name: up-down-classifier
      image:  us-docker.pkg.dev/teknoir/gcr.io/up-down-classifier-triton:latest-amd64-trt10.8-cc8.9-20250508-094640

nvr:
  defaults:
    camera:
      pipeline: |-
        rtspsrc location={{.uri}} protocols=tcp latency=500 name=unmappedsrc
        
        unmappedsrc. ! application/x-rtp,media=video,encoding-name=H264 ! rtpjitterbuffer ! rtph264depay ! h264parse config-interval=-1 ! video/x-h264,stream-format=byte-stream,alignment=au ! nvv4l2decoder name=src
        
        src.
          ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! queue 
          ! queue ! nvmux.sink_0 nvstreammux name=nvmux batch-size=4 width=1920 height=1080 
          ! queue ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 
          ! queue ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 
          ! queue ! nvstreamdemux name=nvdemux 
        
        nvdemux.src_0 
          ! queue ! tee name=tee
        
        tee.
          ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1
          ! queue ! nvvideoconvert ! queue 
          ! queue ! nvjpegenc quality=75 ! appsink sync=0 name=mqttsink 
        
        tee.
          ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 
          ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink 
        
        tee.
          ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 
          ! queue ! nvvideoconvert ! queue ! videorate ! video/x-raw,framerate=10/1 
          ! queue ! nvvideoconvert 
          ! queue ! nvv4l2h264enc copy-meta=true profile=7 control-rate=1 bitrate=3000000 iframeinterval=5 
          ! queue ! h264parse ! queue ! splitmuxsink muxer-properties=properties,streamable=true,moov-relocation=true send-keyframe-requests=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=2880 name=splitmux
    mqtt:
      # Send events without inference calculated
      nonInferenceEvents: false
      # Send events without motion detected
      nonMotionEvents: true
    motion:
      # Number of frames to skip inference when no motion detected
      inactiveInterval: 900
      # Number of frames to skip inference when motion is detected
      activeInterval: 3
    image:
      # AMD64
      tag: ds7.1-gst1.24.12
    nvdsanalytics:
      enabled: true
      config: |
        [property]
        enable=0
        config-width=1920
        config-height=1080
        osd-mode=0
        display-font-size=25
  instances: []
  
observatory-pipeline:
  defaults:
    debugLevel: INFO

    image:
      tag: feature-multicamid-7672449

    labels:
      teamspace: "victra-poc"
      domain: "teknoir.cloud"

    historian:
      recordDetectionsInterval: 50 # ms
      objectsToFilter: "person,weapon,gun" # not interested in vehicles

    alerts:
      personDownInterval: 10
      personDownScoreThreshold: 0.85
      personUpScoreThreshold: 0.75
      personDownUpTotalCountThreshold: 10

      alertHeatmapAlertsToFilter: "loitering,person_down,weapon,hands_up"
      alertHeatmapHardSupression: true
      handsUpInterval: 500 # milliseconds
      handsUpWindow: 1 # seconds
      minHandsUpDetectionsPerSecond: 1.2 # per second

    weaponsDetection:
      scoreThreshold: 0.75 # score threshold
      interval: 500 # milliseconds
      window: 1 # seconds
      minDetectionsPerSecond: 1.8 # per second

    clickhouse:
      detectionRetention: 1 # hours
      movementRetention: 24 # hours
      inferenceRetention: 1 # hours
      alertRetention: 24 # hours
      resources:
        limits:
          cpu: 2000m
          memory: 12Gi
        requests:
          cpu: 10m
          memory: 50Mi

    keydb:
      resources:
        limits:
          cpu: 2000m
          memory: 12Gi
        requests:
          cpu: 10m
          memory: 50Mi

    file-transfer:
      defaults:
        debugLevel: INFO

        labels:
          namespace: "victra-poc"
          domain: "teknoir.cloud"

        resources:
          limits:
            cpu: 2000m
            memory: 5Gi
          requests:
            cpu: 10m
            memory: 50Mi

#  streams:
#    - stream: update-frame-rate-control
#      mqtt:
#        topicDetections: "camera/frames/#"
#    - stream: record-detections
#      mqtt:
#        topicDetections: "camera/frames/#"
#    - stream: update-movements
#    - stream: filter-movements
#    # ALERTS
#    - stream: loitering
#    - stream: person-down
#    - stream: safe-open
#    # ALERT PROCESSING
#    - stream: update-alerts
#    - stream: make-clip
#      video:
#        mountSegmentPath: true
#        mountClipTempPath: true