triton:
  modelRepositoryPath: /opt/teknoir/models
  models:
    - name: rtdetr
      image: us-docker.pkg.dev/teknoir/gcr.io/rtdetr-triton:latest-amd64-trt10.8-cc8.9-20250505-105553
    - name: rtdetr-weapons
      image: us-docker.pkg.dev/teknoir/gcr.io/rtdetr-weapons-triton:latest
    - name: resnet50-pose-estimation
      image:  us-docker.pkg.dev/teknoir/gcr.io/resnet50-pose-estimation-triton:latest-amd64-trt10.8-cc8.9-20250507-065729
    - name: up-down-classifier
      image:  us-docker.pkg.dev/teknoir/gcr.io/up-down-classifier-triton:latest-amd64-trt10.8-cc8.9-20250508-094640

nvr:
  defaults:
    camera:
      pipeline: rtspsrc protocols=tcp timeout=10000000 location={{.uri}} latency=1000 ! queue ! rtpjitterbuffer latency=1500 ! queue ! rtph265depay ! queue ! nvv4l2decoder ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! queue ! m.sink_0 nvstreammux name=m batch-size=4 width=1920 height=1080 ! queue ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=15 ! queue ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5 ! queue ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 ! queue ! nvstreamdemux name=d d.src_0 ! queue ! tee name=t t. ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! nvv4l2h265enc iframeinterval=10 ! queue ! h265parse ! queue ! splitmuxsink sink=nvdsfilesink muxer-properties=properties,streamable=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=160 t. ! queue ! nvdsanalytics config-file=/app/config/config_nvdsanalytics.txt ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1 ! nvvideoconvert ! queue ! nvjpegenc quality=55 ! appsink sync=0 name=mqttsink t. ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 ! nvvideoconvert ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink
    mqtt:
      # Send events without inference calculated
      nonInferenceEvents: false
      # Send events without motion detected
      nonMotionEvents: true
    motion:
      # Number of frames to skip inference when no motion detected
      inactiveInterval: 900
      # Number of frames to skip inference when motion is detected
      activeInterval: 3
    image:
      # AMD64
      tag: ds7.1-gst1.24.12
    nvdsanalytics:
      enabled: true
      config: |
        [property]
        enable=0
        config-width=1920
        config-height=1080
        osd-mode=0
        display-font-size=25
  instances: []
  
observatory-pipeline:
  defaults:
    debugLevel: INFO

    image:
      tag: dev-58f25a3

    labels:
      teamspace: "victra-poc"
      domain: "teknoir.cloud"

    historian:
      recordDetectionsInterval: 50 # ms
      objectsToFilter: "person,weapon,gun" # not interested in vehicles

    clickhouse:
      detectionRetention: 1 # hours
      movementRetention: 24 # hours
      inferenceRetention: 1 # hours
      alertRetention: 24 # hours
      resources:
        limits:
          cpu: 2000m
          memory: 12Gi
        requests:
          cpu: 10m
          memory: 50Mi

    keydb:
      resources:
        limits:
          cpu: 2000m
          memory: 12Gi
        requests:
          cpu: 10m
          memory: 50Mi

    file-transfer:
      defaults:
        debugLevel: INFO

        labels:
          namespace: "victra-poc"
          domain: "teknoir.cloud"

        resources:
          limits:
            cpu: 2000m
            memory: 5Gi
          requests:
            cpu: 10m
            memory: 50Mi

#  streams:
#    - stream: update-frame-rate-control
#      mqtt:
#        topicDetections: "camera/frames/#"
#    - stream: record-detections
#      mqtt:
#        topicDetections: "camera/frames/#"
#    - stream: update-movements
#    - stream: filter-movements
#    # ALERTS
#    - stream: loitering
#    - stream: person-down
#    - stream: safe-open
#    # ALERT PROCESSING
#    - stream: update-alerts
#    - stream: make-clip
#      video:
#        mountSegmentPath: true
#        mountClipTempPath: true