---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nc0009-glenn-school-store
  namespace: default
spec:
  repo: https://teknoir.github.io/victra-poc-helm
  chart: victra-poc
  targetNamespace: default
  valuesContent: |-
    nvr:
      defaults:
        debugLevel: DEBUG
        motion:
          # Number of frames to skip inference when no motion detected
          inactiveInterval: 900
          # Number of frames to skip inference when motion is detected
          activeInterval: 3
        mqtt:
          # Send events without inference calculated
          nonInferenceEvents: false 
        image:
          # AMD64
          tag: ds7-gst1.24.7
        camera:
          pipeline: |-
            rtspsrc location={{.uri}} protocols=tcp latency=500 name=unmappedsrc
      
            unmappedsrc. ! application/x-rtp,media=video,encoding-name=H264 ! rtpjitterbuffer ! rtph264depay ! h264parse config-interval=-1 ! video/x-h264,stream-format=byte-stream,alignment=au ! nvv4l2decoder name=src
  
            src.
              ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=2688,height=1520 ! queue 
              ! queue ! nvmux.sink_0 nvstreammux name=nvmux batch-size=4 width=2688 height=1520 
              ! queue ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 
              ! queue ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5
              ! queue ! nvinferserver config-file-path=/models/resnet50_pose_estimation_config.pbtxt unique-id=200
              ! queue ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 
              ! queue ! nvstreamdemux name=nvdemux 
  
            nvdemux.src_0 
              ! queue ! tee name=tee
  
            tee.
              ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1
              ! queue ! nvvideoconvert ! queue 
              ! queue ! nvjpegenc quality=75 ! appsink sync=0 name=mqttsink 
  
            tee.
              ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 
              ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink 
  
            tee.
              ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 
              ! queue ! nvvideoconvert ! queue ! videorate ! video/x-raw,framerate=10/1 
              ! queue ! nvvideoconvert 
              ! queue ! nvv4l2h264enc copy-meta=true profile=7 control-rate=1 bitrate=3000000 iframeinterval=5 
              ! queue ! h264parse ! queue ! splitmuxsink muxer-properties=properties,streamable=true,moov-relocation=true send-keyframe-requests=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=2880 name=splitmux
  
      instances:
        - name: nc0009-pos
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.113/stream1
  
        - name: nc0009-back-door
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.116/stream1
  
        - name: nc0009-front-door
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.111/stream1
  
        - name: nc0009-height-strip
          camera:
            uri: rtsp://root:Redex1997!@192.168.51.117/live1s1.sdp
            pipeline: |-
              rtspsrc location={{.uri}} protocols=tcp latency=500 name=unmappedsrc
      
              unmappedsrc. ! application/x-rtp,media=video,encoding-name=H264 ! rtpjitterbuffer ! rtph264depay ! h264parse config-interval=-1 ! video/x-h264,stream-format=byte-stream,alignment=au ! nvv4l2decoder name=src
  
              src.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 ! queue 
                ! queue ! nvmux.sink_0 nvstreammux name=nvmux batch-size=4 width=1920 height=1080 
                ! queue ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 
                ! queue ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5
                ! queue ! nvinferserver config-file-path=/models/resnet50_pose_estimation_config.pbtxt unique-id=200
                ! queue ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 
                ! queue ! nvstreamdemux name=nvdemux 
  
              nvdemux.src_0 
                ! queue ! tee name=tee
  
              tee.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,1920],height=[1,1080],pixel-aspect-ratio=1/1
                ! queue ! nvvideoconvert ! queue 
                ! queue ! nvjpegenc quality=75 ! appsink sync=0 name=mqttsink 
  
              tee.
                ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 
                ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink 
  
              tee.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=1920,height=1080 
                ! queue ! nvvideoconvert ! queue ! videorate ! video/x-raw,framerate=10/1 
                ! queue ! nvvideoconvert 
                ! queue ! nvv4l2h264enc copy-meta=true profile=7 control-rate=1 bitrate=3000000 iframeinterval=5 
                ! queue ! h264parse ! queue ! splitmuxsink muxer-properties=properties,streamable=true,moov-relocation=true send-keyframe-requests=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=2880 name=splitmux
  
        - name: nc0009-backroom-safe
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.114/stream2
            pipeline:
              rtspsrc location={{.uri}} protocols=tcp latency=500 name=unmappedsrc
      
              unmappedsrc. ! application/x-rtp,media=video,encoding-name=H264 ! rtpjitterbuffer ! rtph264depay ! h264parse config-interval=-1 ! video/x-h264,stream-format=byte-stream,alignment=au ! nvv4l2decoder name=src
  
              src.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=4000,height=3000 ! queue 
                ! queue ! nvmux.sink_0 nvstreammux name=nvmux batch-size=4 width=4000 height=3000 
                ! queue ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 
                ! queue ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5
                ! queue ! nvinferserver config-file-path=/models/resnet50_pose_estimation_config.pbtxt unique-id=200
                ! queue ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 
                ! queue ! nvstreamdemux name=nvdemux 
  
              nvdemux.src_0 
                ! queue ! tee name=tee
  
              tee.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,2000],height=[1,1500],pixel-aspect-ratio=1/1
                ! queue ! nvvideoconvert ! queue 
                ! queue ! nvjpegenc quality=65 ! appsink sync=0 name=mqttsink 
  
              tee.
                ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 
                ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink 
  
              tee.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=2000,height=1500 
                ! queue ! nvvideoconvert ! queue ! videorate ! video/x-raw,framerate=10/1 
                ! queue ! nvvideoconvert 
                ! queue ! nvv4l2h264enc copy-meta=true profile=7 control-rate=1 bitrate=3000000 iframeinterval=5 
                ! queue ! h264parse ! queue ! splitmuxsink muxer-properties=properties,streamable=true,moov-relocation=true send-keyframe-requests=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=2880 name=splitmux
  
        - name: nc0009-salefloor
          camera:
            uri: rtsp://admin:Redex1997!@192.168.51.112/stream2
            pipeline:
              rtspsrc location={{.uri}} protocols=tcp latency=500 name=unmappedsrc
      
              unmappedsrc. ! application/x-rtp,media=video,encoding-name=H264 ! rtpjitterbuffer ! rtph264depay ! h264parse config-interval=-1 ! video/x-h264,stream-format=byte-stream,alignment=au ! nvv4l2decoder name=src
  
              src.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=4000,height=3000 ! queue 
                ! queue ! nvmux.sink_0 nvstreammux name=nvmux batch-size=4 width=4000 height=3000 
                ! queue ! nvinferserver name=nvis config-file-path=/models/rtdetr_config.pbtxt unique-id=2 interval=5 
                ! queue ! nvinferserver config-file-path=/models/up_down_classifier_config.pbtxt unique-id=5
                ! queue ! nvinferserver config-file-path=/models/resnet50_pose_estimation_config.pbtxt unique-id=200
                ! queue ! nvtracker tracker-width=640 tracker-height=384 ll-lib-file=/opt/nvidia/deepstream/deepstream/lib/libnvds_nvmultiobjecttracker.so ll-config-file=/models/config_tracker_NvDeepSORT.yml compute-hw=2 gpu-id=0 
                ! queue ! nvstreamdemux name=nvdemux 
  
              nvdemux.src_0 
                ! queue ! tee name=tee
  
              tee.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=[1,2000],height=[1,1500],pixel-aspect-ratio=1/1
                ! queue ! nvvideoconvert ! queue 
                ! queue ! nvjpegenc quality=65 ! appsink sync=0 name=mqttsink 
  
              tee.
                ! queue ! nvvideoconvert compute-hw=GPU ! video/x-raw,format=RGB,width=[1,640],height=[1,360],pixel-aspect-ratio=1/1 
                ! queue ! motioncells threshold=0.00005 gridx=32 gridy=18 ! fakesink 
  
              tee.
                ! queue ! nvvideoconvert ! video/x-raw(memory:NVMM),width=2000,height=1500 
                ! queue ! nvvideoconvert ! queue ! videorate ! video/x-raw,framerate=10/1 
                ! queue ! nvvideoconvert 
                ! queue ! nvv4l2h264enc copy-meta=true profile=7 control-rate=1 bitrate=3000000 iframeinterval=5 
                ! queue ! h264parse ! queue ! splitmuxsink muxer-properties=properties,streamable=true,moov-relocation=true send-keyframe-requests=true location=/app/videos/{{.camera_id}}_%05d.mp4 max-size-time=15000000000 max-files=2880 name=splitmux

    observatory-pipeline:
      defaults:
        debugLevel: DEBUG
  
        image:
          tag: face-cover-alert-45f3078
  
        labels:
          deviceID: "victra-poc-01"
          namespace: "victra-poc"
          domain: "teknoir.cloud"
  
        #mqtt:
        #  topicToeEventsAlerts: toe/events
  
      streams:
        - stream: update-frame-rate-control
        - stream: record-detections
        - stream: update-movements
        - stream: compreface
          mqtt:
            topicFaces: "toe/events/faces"
          facerec:
            compreFaceApiKey: "00000000-0000-0000-0000-000000000002"
            faceRecThreshold: 0.9
            faceImageSize: 100
        # ALERTS
        #- stream: motion
        - stream: loitering
        - stream: person-down
        - stream: line-crossing
        - stream: hands-up
        - stream: running
        - stream: face-cover
        # ALERT PROCESSING
        - stream: update-alerts
  
      clickhouse:
        resources:
          limits:
            cpu: 2000m
            memory: 12Gi
          requests:
            cpu: 10m
            memory: 50Mi
        nodePort:
          enabled: true
      keydb:
        nodePort:
          enabled: true
      
      file-transfer:
        defaults:
          debugLevel: DEBUG
  
          labels:
            deviceID: "victra-poc-01"
            namespace: "victra-poc"
            domain: "teknoir.cloud"
  
          resources:
            limits:
              cpu: 2000m
              memory: 5Gi
            requests:
              cpu: 10m
              memory: 50Mi
        streams:
          - stream: prepare-file
            video:
              mountSegmentPath: true
              mountClipTempPath: true
          - stream: transfer-file      
            video:
              mountSegmentPath: true
              mountClipTempPath: true

