# Be aware that this only works if you create a version for the chart in the format X.Y.Z-something
name: Beta-release Charts (add hidden versions of the chart)

on:
  push:
    branches:
      - beta

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Check chart beta version
        id: check_chart_version
        run: |
          CHART_VERSION=$(find charts -name Chart.yaml -exec grep '^version:' {} \; | awk '{print $2}')
          if [[ ! "$CHART_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+-.+ ]]; then
          echo "Chart version $CHART_VERSION is not in the format X.Y.Z-something"
          exit 1
          fi
          echo "Chart version $CHART_VERSION is valid for beta release"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
